### PR TITLE
feat!: add no-loader-import-specifier rule (#122)

### LINKED ISSUE #122: Lint for inappropriate use of SCSS/CSS import return values
These should only ever be imported for their side-effects:

```javascript
import './My.scss';
```

Never assigned:

```javascript
import bad from './My.scss';
```

### PR DESCRIPTION
**Pull request by wincent**
This rule prevents us from providing useless import specifiers when importing SCSS via the loader:

```js
import useless from './styles.scss';
```
These modules should only be imported for their side-effects; ie:

```js
import './styles.scss';
```

As noted in the docs, we might want to lint for other kinds of non-JS resources in the future, but for now ".scss" is the only file type that we actually have configured to load via this mechanism.

Test plan: Copy the code over to a liferay-portal repo (eg. with `cp -R ~/code/eslint-config-liferay/{portal.js,plugins} node_modules/eslint-config-liferay`) and then introduce a fake error; see this in the lint run output (`yarn checkFormat`):

    modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/treeview/Treeview.js
      24:1  error  SCSS resources should be imported only for side-effects  liferay-portal/no-loader-import-specifier

Closes: https://github.com/liferay/eslint-config-liferay/issues/122

### CODE REVIEW

**Comment by jbalsas** [comment]
We could add `.soy` to the mix here... even if just for the sake of correctness and until we've gotten rid of them all...

**Comment by wincent** [comment]
> We could add `.soy` to the mix here...

Ah, good idea!

**Comment by jbalsas** [comment]
Although now that I think of it, we might actually be using their return, so scratch that, I need coffee ☕️ 

We are loading some `.js` files just so they load `.soy` templates, but that'll be a whole different story

**Comment by wincent** [comment]
Common pattern:

```js
import './ValidationRegister.soy.js';

Soy.register(Validation, templates);
```

and:

```js
import './TextRegister.soy.js';
```

**Pull request merged**
